"""
Comprehensive US state + city database for systematic school scraping.

States are ordered with Texas first, then alphabetically.
Each state includes its top cities by population plus key metro areas
to ensure thorough geographic coverage without gaps.
"""

# State abbreviation mapping
STATE_ABBREV = {
    "Texas": "TX", "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ",
    "Arkansas": "AR", "California": "CA", "Colorado": "CO", "Connecticut": "CT",
    "Delaware": "DE", "Florida": "FL", "Georgia": "GA", "Hawaii": "HI",
    "Idaho": "ID", "Illinois": "IL", "Indiana": "IN", "Iowa": "IA",
    "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME",
    "Maryland": "MD", "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN",
    "Mississippi": "MS", "Missouri": "MO", "Montana": "MT", "Nebraska": "NE",
    "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM",
    "New York": "NY", "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH",
    "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI",
    "South Carolina": "SC", "South Dakota": "SD", "Tennessee": "TN", "Utah": "UT",
    "Vermont": "VT", "Virginia": "VA", "Washington": "WA", "West Virginia": "WV",
    "Wisconsin": "WI", "Wyoming": "WY"
}

# Texas FIRST (user's priority), then all other states alphabetically
# Each state has comprehensive city coverage for thorough scraping
STATES_CITIES = {
    "Texas": [
        "Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso",
        "Arlington", "Corpus Christi", "Plano", "Lubbock", "Irving", "Laredo",
        "Garland", "Frisco", "McKinney", "Amarillo", "Grand Prairie", "Brownsville",
        "Killeen", "Pasadena", "Midland", "McAllen", "Denton", "Carrollton",
        "Round Rock", "Waco", "Abilene", "Pearland", "Odessa", "College Station",
        "Richardson", "Beaumont", "League City", "The Woodlands", "Tyler",
        "Sugar Land", "Allen", "Wichita Falls", "Conroe", "San Angelo",
        "New Braunfels", "Galveston", "Victoria", "Temple", "San Marcos",
        "Georgetown", "Mansfield", "Cedar Park", "Rowlett", "Pflugerville",
        "Euless", "DeSoto", "Grapevine", "Bedford", "Lewisville",
        "Flower Mound", "Harlingen", "North Richland Hills", "Baytown", "Missouri City",
        "Pharr", "Cedar Hill", "Friendswood", "Katy", "Tomball",
        "Spring", "Humble", "Wylie", "Prosper", "Rockwall",
        "Coppell", "Southlake", "Colleyville", "Trophy Club", "Hurst",
        "Burleson", "Cleburne", "Weatherford", "Mesquite", "Lancaster",
        "Duncanville", "Waxahachie", "Corsicana", "Lufkin", "Nacogdoches",
        "Sherman", "Denison", "Texarkana", "Longview", "Marshall",
        "Paris", "Greenville", "Huntsville", "Bryan", "Copperas Cove",
        "Harker Heights", "Belton", "Stephenville", "Eagle Pass", "Del Rio",
        "Edinburg", "Mission", "Weslaco", "Rio Grande City", "Kingsville",
        "Alice", "Seguin", "Kerrville", "Fredericksburg", "Boerne",
        "Dripping Springs", "Bastrop", "Buda", "Kyle", "Lockhart",
        "Marble Falls", "Llano", "Lampasas", "Coppell", "Murphy",
        "Sachse", "Forney", "Terrell", "Ennis", "Midlothian",
        "Red Oak", "Glenn Heights", "Seagoville", "Balch Springs", "Hutchins",
        "Celina", "Anna", "Princeton", "Melissa", "Aubrey",
        "Little Elm", "Sanger", "Argyle", "Justin", "Roanoke",
        "Keller", "Haslet", "Fort Stockton", "Pecos", "Alpine",
        "Uvalde", "San Benito", "Los Fresnos", "Port Isabel", "South Padre Island",
    ],
    "Alabama": [
        "Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa",
        "Hoover", "Dothan", "Auburn", "Decatur", "Madison",
        "Florence", "Gadsden", "Vestavia Hills", "Prattville", "Phenix City",
        "Alabaster", "Opelika", "Enterprise", "Homewood", "Northport",
        "Anniston", "Daphne", "Pelham", "Oxford", "Albertville",
        "Troy", "Jacksonville", "Selma", "Trussville", "Mountain Brook",
    ],
    "Alaska": [
        "Anchorage", "Juneau", "Fairbanks", "Wasilla", "Sitka",
        "Ketchikan", "Kenai", "Kodiak", "Bethel", "Palmer",
        "Homer", "Soldotna", "Valdez", "Nome", "Seward",
    ],
    "Arizona": [
        "Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale",
        "Glendale", "Gilbert", "Tempe", "Peoria", "Surprise",
        "Yuma", "Avondale", "Goodyear", "Flagstaff", "Buckeye",
        "Lake Havasu City", "Maricopa", "Casa Grande", "Queen Creek", "Prescott",
        "Bullhead City", "San Tan Valley", "Sierra Vista", "Apache Junction", "Oro Valley",
        "Prescott Valley", "Marana", "Sahuarita", "Fountain Hills", "Sedona",
    ],
    "Arkansas": [
        "Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro",
        "North Little Rock", "Conway", "Rogers", "Pine Bluff", "Bentonville",
        "Hot Springs", "Benton", "Texarkana", "Sherwood", "Jacksonville",
        "Russellville", "Cabot", "Paragould", "Bella Vista", "Van Buren",
        "West Memphis", "Maumelle", "Searcy", "Bryant", "Siloam Springs",
    ],
    "California": [
        "Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno",
        "Sacramento", "Long Beach", "Oakland", "Bakersfield", "Anaheim",
        "Santa Ana", "Riverside", "Stockton", "Irvine", "Chula Vista",
        "Fremont", "San Bernardino", "Modesto", "Moreno Valley", "Fontana",
        "Glendale", "Huntington Beach", "Santa Clarita", "Garden Grove", "Oceanside",
        "Rancho Cucamonga", "Ontario", "Santa Rosa", "Elk Grove", "Corona",
        "Lancaster", "Palmdale", "Salinas", "Pomona", "Hayward",
        "Escondido", "Sunnyvale", "Torrance", "Pasadena", "Orange",
        "Fullerton", "Thousand Oaks", "Roseville", "Concord", "Simi Valley",
        "Santa Maria", "Victorville", "Berkeley", "El Monte", "Downey",
        "Costa Mesa", "Carlsbad", "San Marcos", "Temecula", "Murrieta",
        "Clovis", "Redding", "Napa", "Walnut Creek", "Palo Alto",
    ],
    "Colorado": [
        "Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood",
        "Thornton", "Arvada", "Westminster", "Pueblo", "Centennial",
        "Boulder", "Greeley", "Longmont", "Loveland", "Broomfield",
        "Castle Rock", "Commerce City", "Parker", "Brighton", "Littleton",
        "Northglenn", "Grand Junction", "Erie", "Englewood", "Durango",
        "Steamboat Springs", "Aspen", "Telluride", "Golden", "Highlands Ranch",
    ],
    "Connecticut": [
        "Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury",
        "Norwalk", "Danbury", "New Britain", "Bristol", "West Haven",
        "Meriden", "Milford", "Middletown", "Shelton", "Norwich",
        "Torrington", "Groton", "Glastonbury", "Greenwich", "Fairfield",
        "Westport", "Darien", "New Canaan", "Ridgefield", "Guilford",
    ],
    "Delaware": [
        "Wilmington", "Dover", "Newark", "Middletown", "Bear",
        "Glasgow", "Hockessin", "Brookside", "Smyrna", "Milford",
        "Seaford", "Georgetown", "Lewes", "Rehoboth Beach", "Elsmere",
    ],
    "Florida": [
        "Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg",
        "Hialeah", "Port St. Lucie", "Cape Coral", "Tallahassee", "Fort Lauderdale",
        "Pembroke Pines", "Hollywood", "Gainesville", "Miramar", "Coral Springs",
        "Palm Bay", "West Palm Beach", "Clearwater", "Lakeland", "Pompano Beach",
        "Davie", "Miami Gardens", "Sunrise", "Boca Raton", "Deltona",
        "Plantation", "Palm Coast", "Deerfield Beach", "Fort Myers", "Melbourne",
        "Largo", "Kissimmee", "Boynton Beach", "Homestead", "Sarasota",
        "Bradenton", "Ocala", "Naples", "Jupiter", "Coconut Creek",
        "Sanford", "Winter Garden", "Clermont", "Winter Haven", "Bonita Springs",
        "Destin", "Panama City", "Pensacola", "Daytona Beach", "Key West",
    ],
    "Georgia": [
        "Atlanta", "Augusta", "Columbus", "Savannah", "Athens",
        "Sandy Springs", "Roswell", "Macon", "Johns Creek", "Albany",
        "Warner Robins", "Alpharetta", "Marietta", "Valdosta", "Smyrna",
        "Dunwoody", "Brookhaven", "Peachtree City", "Kennesaw", "Dalton",
        "Gainesville", "Newnan", "Milton", "Woodstock", "Canton",
        "Hinesville", "Statesboro", "Cartersville", "Douglasville", "Rome",
    ],
    "Hawaii": [
        "Honolulu", "Pearl City", "Hilo", "Kailua", "Waipahu",
        "Kaneohe", "Mililani Town", "Kahului", "Ewa Beach", "Kapolei",
        "Kihei", "Lahaina", "Wailuku", "Aiea", "Makakilo",
    ],
    "Idaho": [
        "Boise", "Meridian", "Nampa", "Idaho Falls", "Caldwell",
        "Pocatello", "Coeur d'Alene", "Twin Falls", "Post Falls", "Eagle",
        "Lewiston", "Moscow", "Rexburg", "Kuna", "Mountain Home",
        "Garden City", "Chubbuck", "Ammon", "Star", "Sandpoint",
    ],
    "Illinois": [
        "Chicago", "Aurora", "Joliet", "Naperville", "Rockford",
        "Springfield", "Elgin", "Peoria", "Champaign", "Waukegan",
        "Cicero", "Bloomington", "Arlington Heights", "Evanston", "Schaumburg",
        "Bolingbrook", "Decatur", "Palatine", "Skokie", "Des Plaines",
        "Orland Park", "Tinley Park", "Oak Lawn", "Berwyn", "Normal",
        "Wheaton", "Downers Grove", "Oak Park", "Elmhurst", "Highland Park",
    ],
    "Indiana": [
        "Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel",
        "Fishers", "Bloomington", "Hammond", "Gary", "Lafayette",
        "Muncie", "Terre Haute", "Noblesville", "Columbus", "Greenwood",
        "Elkhart", "Anderson", "Kokomo", "Lawrence", "New Albany",
        "Westfield", "Zionsville", "Avon", "Plainfield", "Brownsburg",
    ],
    "Iowa": [
        "Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City",
        "Waterloo", "Ames", "West Des Moines", "Council Bluffs", "Ankeny",
        "Dubuque", "Urbandale", "Cedar Falls", "Marion", "Bettendorf",
        "Mason City", "Marshalltown", "Clinton", "Burlington", "Waukee",
    ],
    "Kansas": [
        "Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka",
        "Lawrence", "Shawnee", "Manhattan", "Lenexa", "Salina",
        "Hutchinson", "Leavenworth", "Leawood", "Dodge City", "Garden City",
        "Emporia", "Derby", "Junction City", "Prairie Village", "Liberal",
    ],
    "Kentucky": [
        "Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington",
        "Richmond", "Georgetown", "Florence", "Hopkinsville", "Nicholasville",
        "Elizabethtown", "Henderson", "Frankfort", "Paducah", "Ashland",
        "Radcliff", "Murray", "Danville", "Erlanger", "Burlington",
    ],
    "Louisiana": [
        "New Orleans", "Baton Rouge", "Shreveport", "Metairie", "Lafayette",
        "Lake Charles", "Kenner", "Bossier City", "Monroe", "Alexandria",
        "Prairieville", "Houma", "Central", "Slidell", "Ruston",
        "New Iberia", "Sulphur", "Zachary", "Natchitoches", "Hammond",
    ],
    "Maine": [
        "Portland", "Lewiston", "Bangor", "South Portland", "Auburn",
        "Biddeford", "Sanford", "Brunswick", "Saco", "Scarborough",
        "Westbrook", "Augusta", "Gorham", "Windham", "Waterville",
    ],
    "Maryland": [
        "Baltimore", "Columbia", "Germantown", "Silver Spring", "Waldorf",
        "Glen Burnie", "Ellicott City", "Frederick", "Dundalk", "Rockville",
        "Bethesda", "Towson", "Bowie", "Gaithersburg", "Annapolis",
        "College Park", "Salisbury", "Hagerstown", "Laurel", "Severna Park",
        "Catonsville", "Odenton", "Pasadena", "Owings Mills", "Potomac",
    ],
    "Massachusetts": [
        "Boston", "Worcester", "Springfield", "Cambridge", "Lowell",
        "Brockton", "New Bedford", "Quincy", "Lynn", "Fall River",
        "Newton", "Somerville", "Lawrence", "Framingham", "Haverhill",
        "Waltham", "Brookline", "Plymouth", "Medford", "Malden",
        "Taunton", "Chicopee", "Weymouth", "Revere", "Peabody",
        "Wellesley", "Lexington", "Needham", "Natick", "Concord",
    ],
    "Michigan": [
        "Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor",
        "Lansing", "Flint", "Dearborn", "Livonia", "Troy",
        "Farmington Hills", "Kalamazoo", "Canton", "Wyoming", "Southfield",
        "Rochester Hills", "Taylor", "Royal Oak", "Novi", "Pontiac",
        "St. Clair Shores", "Dearborn Heights", "Westland", "Bloomfield Hills", "Holland",
        "Muskegon", "Saginaw", "Battle Creek", "East Lansing", "Traverse City",
    ],
    "Minnesota": [
        "Minneapolis", "Saint Paul", "Rochester", "Bloomington", "Duluth",
        "Brooklyn Park", "Plymouth", "Maple Grove", "Woodbury", "St. Cloud",
        "Lakeville", "Eagan", "Eden Prairie", "Blaine", "Burnsville",
        "Minnetonka", "Apple Valley", "Edina", "Mankato", "St. Louis Park",
        "Moorhead", "Shakopee", "Maplewood", "Coon Rapids", "Richfield",
    ],
    "Mississippi": [
        "Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi",
        "Meridian", "Tupelo", "Olive Branch", "Greenville", "Horn Lake",
        "Clinton", "Pearl", "Madison", "Starkville", "Ridgeland",
        "Columbus", "Vicksburg", "Brandon", "Oxford", "Pascagoula",
    ],
    "Missouri": [
        "Kansas City", "St. Louis", "Springfield", "Columbia", "Independence",
        "Lee's Summit", "O'Fallon", "St. Joseph", "St. Charles", "Blue Springs",
        "St. Peters", "Florissant", "Joplin", "Chesterfield", "Jefferson City",
        "Cape Girardeau", "Wildwood", "University City", "Ballwin", "Kirkwood",
        "Wentzville", "Liberty", "Raymore", "Gladstone", "Sedalia",
    ],
    "Montana": [
        "Billings", "Missoula", "Great Falls", "Bozeman", "Butte",
        "Helena", "Kalispell", "Havre", "Anaconda", "Miles City",
        "Belgrade", "Livingston", "Laurel", "Whitefish", "Sidney",
    ],
    "Nebraska": [
        "Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney",
        "Fremont", "Hastings", "Norfolk", "North Platte", "Papillion",
        "Columbus", "La Vista", "Scottsbluff", "South Sioux City", "Beatrice",
    ],
    "Nevada": [
        "Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks",
        "Carson City", "Fernley", "Elko", "Mesquite", "Boulder City",
        "Fallon", "Winnemucca", "West Wendover", "Ely", "Pahrump",
    ],
    "New Hampshire": [
        "Manchester", "Nashua", "Concord", "Derry", "Dover",
        "Rochester", "Salem", "Merrimack", "Hudson", "Londonderry",
        "Keene", "Bedford", "Portsmouth", "Laconia", "Lebanon",
    ],
    "New Jersey": [
        "Newark", "Jersey City", "Paterson", "Elizabeth", "Lakewood",
        "Edison", "Woodbridge", "Toms River", "Hamilton", "Trenton",
        "Clifton", "Camden", "Brick", "Cherry Hill", "Passaic",
        "Middletown", "Union City", "Old Bridge", "Gloucester", "North Bergen",
        "Vineland", "Bayonne", "East Orange", "Franklin", "New Brunswick",
        "Princeton", "Morristown", "Montclair", "Hoboken", "Summit",
    ],
    "New Mexico": [
        "Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell",
        "Farmington", "South Valley", "Clovis", "Hobbs", "Alamogordo",
        "Carlsbad", "Gallup", "Deming", "Los Lunas", "Chaparral",
        "Las Vegas", "Sunland Park", "Artesia", "Silver City", "Espanola",
    ],
    "New York": [
        "New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse",
        "Albany", "New Rochelle", "Mount Vernon", "Schenectady", "Utica",
        "White Plains", "Troy", "Niagara Falls", "Binghamton", "Freeport",
        "Long Beach", "Saratoga Springs", "Ithaca", "Poughkeepsie", "Hempstead",
        "Valley Stream", "Mamaroneck", "Harrison", "Rye", "Garden City",
        "Great Neck", "Chappaqua", "Bronxville", "Scarsdale", "Manhasset",
    ],
    "North Carolina": [
        "Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem",
        "Fayetteville", "Cary", "Wilmington", "High Point", "Concord",
        "Greenville", "Asheville", "Gastonia", "Jacksonville", "Chapel Hill",
        "Huntersville", "Apex", "Burlington", "Kannapolis", "Mooresville",
        "Rocky Mount", "Wilson", "Hickory", "Wake Forest", "Matthews",
        "Holly Springs", "Indian Trail", "Fuquay-Varina", "Cornelius", "Mint Hill",
    ],
    "North Dakota": [
        "Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo",
        "Williston", "Dickinson", "Mandan", "Jamestown", "Wahpeton",
        "Devils Lake", "Valley City", "Watford City", "Beulah", "Rugby",
    ],
    "Ohio": [
        "Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron",
        "Dayton", "Parma", "Canton", "Youngstown", "Lorain",
        "Hamilton", "Springfield", "Kettering", "Elyria", "Lakewood",
        "Cuyahoga Falls", "Dublin", "Beavercreek", "Strongsville", "Westerville",
        "Mentor", "Hilliard", "Upper Arlington", "Fairfield", "Mason",
        "Findlay", "Lima", "Mansfield", "Newark", "Zanesville",
    ],
    "Oklahoma": [
        "Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond",
        "Lawton", "Moore", "Midwest City", "Enid", "Stillwater",
        "Muskogee", "Bartlesville", "Owasso", "Shawnee", "Yukon",
        "Bixby", "Jenks", "Ardmore", "Duncan", "Ponca City",
    ],
    "Oregon": [
        "Portland", "Salem", "Eugene", "Gresham", "Hillsboro",
        "Beaverton", "Bend", "Medford", "Springfield", "Corvallis",
        "Albany", "Tigard", "Lake Oswego", "Keizer", "Grants Pass",
        "Oregon City", "McMinnville", "Redmond", "Tualatin", "West Linn",
        "Ashland", "Woodburn", "Newberg", "Roseburg", "Wilsonville",
    ],
    "Pennsylvania": [
        "Philadelphia", "Pittsburgh", "Allentown", "Reading", "Scranton",
        "Bethlehem", "Lancaster", "Harrisburg", "York", "Erie",
        "Wilkes-Barre", "Chester", "State College", "Easton", "Lebanon",
        "Norristown", "Pottstown", "Williamsport", "Chambersburg", "King of Prussia",
        "West Chester", "Doylestown", "Media", "Wayne", "Bryn Mawr",
        "Abington", "Haverford", "Radnor", "Lower Merion", "Bala Cynwyd",
    ],
    "Rhode Island": [
        "Providence", "Warwick", "Cranston", "Pawtucket", "East Providence",
        "Woonsocket", "Newport", "Central Falls", "Westerly", "North Kingstown",
        "Bristol", "South Kingstown", "Barrington", "Cumberland", "Smithfield",
    ],
    "South Carolina": [
        "Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Rock Hill",
        "Greenville", "Summerville", "Goose Creek", "Hilton Head Island", "Florence",
        "Spartanburg", "Sumter", "Myrtle Beach", "Greer", "Aiken",
        "Anderson", "Mauldin", "Bluffton", "Conway", "Clemson",
        "Easley", "Simpsonville", "Fort Mill", "Lexington", "Irmo",
    ],
    "South Dakota": [
        "Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown",
        "Mitchell", "Yankton", "Huron", "Pierre", "Spearfish",
        "Vermillion", "Brandon", "Box Elder", "Madison", "Sturgis",
    ],
    "Tennessee": [
        "Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville",
        "Murfreesboro", "Franklin", "Jackson", "Johnson City", "Bartlett",
        "Hendersonville", "Kingsport", "Collierville", "Smyrna", "Cleveland",
        "Brentwood", "Germantown", "Spring Hill", "Columbia", "La Vergne",
        "Gallatin", "Cookeville", "Lebanon", "Mount Juliet", "Maryville",
    ],
    "Utah": [
        "Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem",
        "Sandy", "St. George", "Ogden", "Layton", "South Jordan",
        "Lehi", "Millcreek", "Taylorsville", "Logan", "Murray",
        "Draper", "Bountiful", "Riverton", "Herriman", "Spanish Fork",
        "Pleasant Grove", "Springville", "Eagle Mountain", "Saratoga Springs", "American Fork",
    ],
    "Vermont": [
        "Burlington", "South Burlington", "Rutland", "Barre", "Montpelier",
        "Winooski", "St. Albans", "Newport", "Vergennes", "Brattleboro",
        "Bennington", "Norwich", "Stowe", "Woodstock", "Middlebury",
    ],
    "Virginia": [
        "Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News",
        "Alexandria", "Hampton", "Roanoke", "Portsmouth", "Suffolk",
        "Lynchburg", "Harrisonburg", "Leesburg", "Charlottesville", "Danville",
        "Manassas", "Fredericksburg", "Winchester", "Salem", "Staunton",
        "McLean", "Fairfax", "Arlington", "Reston", "Ashburn",
        "Centreville", "Herndon", "Sterling", "Great Falls", "Vienna",
    ],
    "Washington": [
        "Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue",
        "Kent", "Everett", "Renton", "Spokane Valley", "Federal Way",
        "Yakima", "Kirkland", "Bellingham", "Kennewick", "Auburn",
        "Pasco", "Marysville", "Redmond", "Lakewood", "Sammamish",
        "Shoreline", "Olympia", "Burien", "Lacey", "Edmonds",
        "Richland", "Bothell", "Issaquah", "Mercer Island", "Bainbridge Island",
    ],
    "West Virginia": [
        "Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling",
        "Weirton", "Fairmont", "Martinsburg", "Beckley", "Clarksburg",
        "South Charleston", "Teays Valley", "St. Albans", "Vienna", "Bluefield",
    ],
    "Wisconsin": [
        "Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine",
        "Appleton", "Waukesha", "Oshkosh", "Eau Claire", "Janesville",
        "West Allis", "La Crosse", "Sheboygan", "Wauwatosa", "Fond du Lac",
        "New Berlin", "Brookfield", "Wausau", "Greenfield", "Fitchburg",
        "Menomonee Falls", "Franklin", "Oak Creek", "Mequon", "Pewaukee",
    ],
    "Wyoming": [
        "Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs",
        "Sheridan", "Green River", "Evanston", "Riverton", "Jackson",
        "Cody", "Rawlins", "Lander", "Powell", "Douglas",
    ],
}

# Ordered list: Texas first, then all remaining states alphabetically
STATE_ORDER = ["Texas"] + sorted([s for s in STATES_CITIES.keys() if s != "Texas"])

def get_total_queries():
    """Return total number of city entries across all states."""
    return sum(len(cities) for cities in STATES_CITIES.values())
